Check if sd-boot is installed before running

diff --git a/reboot-to b/reboot-to
--- a/reboot-to
+++ b/reboot-to
@@ -1,4 +1,10 @@
 #!/bin/bash
+
+[[ $(bootctl is-installed) == "yes" ]] || {
+	printf "error: systemd-boot is not installed"
+	exit 1
+}
+
 ID=$(awk -v FS== '/^ID=/{print $2}' /etc/os-release)
 targets=()
 if [[ $1 ]]; then
diff --git a/update-sd-boot b/update-sd-boot
--- a/update-sd-boot
+++ b/update-sd-boot
@@ -1,9 +1,15 @@
 #!/bin/bash
+[[ $(bootctl is-installed) == "yes" ]] || {
+	printf "error: systemd-boot is not installed"
+	exit 1
+}
+
 if [[ $(id -u) != 0 ]]; then
 	echo "Run this as root"
 	exit
 fi
+
 cd /
 echo "Updating sd-boot entries."
-find usr/lib/modules/ -mindepth 2 -maxdepth 2 -type f -name 'vmlinuz' |
-	/usr/share/libalpm/scripts/sd-boot-install
+find usr/lib/modules/ -mindepth 2 -maxdepth 2 -type f -name 'vmlinuz' \
+	| /usr/share/libalpm/scripts/sd-boot-install
